#include <stdio.h>
#include "core/type.h"
#include "core/str.h"
#include "core/file.h"

#include "meta/lexer.h"


#define LOG


const char* debug_meta_str = "\033[34m[META]\033[0m";
#define meta_log(format, ...)                 (void)fprintf(stderr, "%s " format, debug_meta_str, ##__VA_ARGS__);




void meta_replace_with_space(String metanote_str) {
    for (s64 i = 0; i < metanote_str.length; i++) {
        metanote_str.data[i] = ' ';
    }
}


/**
 * Meta processing of individual file.
 * It will fwrite generated output to the output file.
 * @Important: output must be opened in "a" mode, in order for this function to properly append generated code.
 */
int meta_process_file(char *file_name, FILE *output_c, FILE *output_h) {
#ifdef LOG
    meta_log("Processing '%s'\n", file_name);
#endif

    
    String _content = read_file_into_str(file_name, &std_allocator);

    if (_content.data == NULL) {
        printf_err("Couldn't read file '%s'\n", file_name);
        return 1;
    }

    
    
    
    // Process _content here.
    Lexer lexer;

    lexer_init(&lexer, _content);

    Token next;
    while(true) {
        next = lexer_next_token(&lexer);

        if (next.type == TOKEN_ZERO) break;


        // Searching for metanotes.
        if (next.type == TOKEN_METANOTE) {
            Token metanote = next;
            next = lexer_next_token(&lexer);
            
            if (next.type != TOKEN_SYMBOL) {
                printf_err("Expected TOKEN_SYMBOL after TOKEN_METANOTE on line %lld.\n", lexer.line_num);
                return 1;
            }
            
            String metanote_str = STR(metanote.str.length + next.str.length, metanote.str.data);
            
            printf("       - Found meta note '%.*s' on line %lld.\n", UNPACK(metanote_str), lexer.line_num);

            meta_replace_with_space(metanote_str);
        }

    }
    


    // Make source file.
    s64 name_length = strlen(file_name);
    if (name_length >= 128) {
        printf_err("File name '%s' is too long, can't create source file.\n", file_name);
        return 1;
    }

    char meta_file_name[128];
    memcpy(meta_file_name, "game/", 5);
    memcpy(meta_file_name + 5, file_name + 6, name_length - 5); // Discarding game_m/ and saving \0 at the end


    if (write_str_to_file(_content, meta_file_name) != 0) {
        printf_err("Couldn't create source file '%s'\n", meta_file_name);
        return 1;
    }


    allocator_free(&std_allocator, _content.data);




    return 0;
}













String meta_generated_comment = CSTR(
        "/**\n"
        " * THIS FILE IS AUTO GENERATED BY META.EXE\n"
        " * DO NOT DELETE THIS FILE\n"
        " *\n"
        " * It will contain auto generated code that then is appended to the main compilation.\n"
        " * Do not add any additional code, it will be overwritten.\n"
        " * Do not delete this file, otherwise makefile won't see it and compilation will fail.\n"
        " */\n"
        );


/**
 * This function overwrites file specified by file_name.
 * Then opens it in "a" mode and returns pointer to it, ready to accept auto generated code.
 * Needs to closed with fclose after use.
 */
FILE *meta_generate(char *file_name) {
    if (write_str_to_file(meta_generated_comment, file_name) != 0) {
        printf_err("Couldn't overwrite meta generated file '%s'\n", file_name);
        return NULL;
    }

    FILE *file = fopen(file_name, "a");
    if (file == NULL) {
        printf_err("Couldn't open meta generated file for appending '%s'.\n", file_name);
        return NULL;
    }

    return file;
}















// Essentially meta programm is compiled into a file and immediately executed as a preprocces.
int main(int argc, char **argv) {
    printf("\n\n");

    
#ifdef LOG
    meta_log("Files passed to meta.exe: ");
    for (int i = 1; i < argc; i++) {
        printf("'%s' ", argv[i]);
    }
    printf("\n");
#endif

    // Preparing meta generated files.
    FILE *meta_generated_c = meta_generate("src/meta_generated.c");
    FILE *meta_generated_h = meta_generate("src/meta_generated.h");

    if (meta_generated_c == NULL || meta_generated_h == NULL) {
        return 1;
    }
    
    for (int i = 1; i < argc; i++) {
        if (meta_process_file(argv[i], meta_generated_c, meta_generated_h) != 0) {
            fclose(meta_generated_c);
            fclose(meta_generated_h);
            return 1;
        }
    }



    fclose(meta_generated_c);
    fclose(meta_generated_h);


    printf("\n\n");

    return 0;
}
