/**
 * THIS FILE IS AUTO GENERATED BY META.EXE
 * DO NOT DELETE THIS FILE
 *
 * It will contain auto generated code that then is appended to the main compilation.
 * Do not add any additional code, it will be overwritten.
 * Do not delete this file, otherwise makefile won't see it and compilation will fail.
 */
